name: RPCharacterPlugin
version: '${project.version}'
main: me.arahis.rpcharacter.RPCharacterPlugin
api-version: '1.21'
commands:
  createchar:
    description: Создает персонажа
    usage: /createchar <role> [name]
    permission: rpch.create
    aliases:
      - crch
  charsetskin:
    description: Изменяет скин выбранного персонажа
    permission: rpch.skin
    usage: /charskin <format[nick/url]> <id> <nick/url> <classic/slim>
    aliases:
      - charskin
      - chsk
      - cs
  charsetrole:
    description: Изменяет роль выбранного персонажа
    usage: /charrole <id> [role]
    permission: rpch.role
    aliases:
      - charrole
      - chro
      - cr
  cachechars:
    permission: rpch.cache
  charsmenu:
    description: Открывает меню персонажей
    aliases:
      - char
      - character
    permission: rpch.menu
  savedata:
    permission: rpch.savedata
  rpchar:
    permission: rpch.admin
